export const ADD_ELEMENT = 'ADD_ELEMENT';
export const PERSIST_DATA = 'PERSIST_DATA';
export const HYDRATE_DATA_DATA = 'HYDRATE_DATA_DATA';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const CHECKED_ELEMENT = 'CHECKED_ELEMENT';
export const EDIT_MODE_ELEMENT = 'EDIT_MODE_ELEMENT';
export const EDIT_TEXT_ELEMENT = 'EDIT_TEXT_ELEMENT';
